feat: 쿠버네티스 기본
HunkiKim/Mantech-Edu pull request #1
Opened 2023-05-15 02:06 UTC by HunkiKim

- Kubernetes 아키텍처
- 노드
    - 마스터 노드
        - Control Plane
            - etcd
            - controller manger
            - api server
            - scheduler
    - 워커 노드
        - kubelet
        - kube-proxy

2023-05-15 12:30 UTC, mantech-mjkim requested changes

2023-05-15 12:30 UTC, mantech-mjkim commented on kubernetes/k8s-basic.md
> +            - 리더,팔로워,후보자 세 가지 역할로 노드를 구성하고 리더 선출, 로그 복제 등의 과정을 통해 분산시스템의 일관성을 유지한다고 하는데 자세하겐 모르겠습니다
https://tech.kakao.com/2021/12/20/kubernetes-etcd/ 에서 RAFT 알고리즘에 대해서 자세히 설명되어 내용 확인해주세요.
RSM 및 용어/리더선출/Log Replication/백업에 대해서 확인하고 다른 내용들은 간단히 참조해도 될 것 같습니다.

2023-05-15 12:30 UTC, mantech-mjkim commented on kubernetes/k8s-basic.md
> +## Kube-proxy
iptables를 이용한 kube-proxy의 네트워크 간단한 통신 방식 이미지를 첨부해주세요.

2023-05-15 12:30 UTC, mantech-mjkim commented on kubernetes/k8s-basic.md
> +# 쿠버네티스 특징
특징에 대한 간략한 설명을 작성해주세요,

2023-05-18 05:19 UTC, HunkiKim commented on kubernetes/k8s-basic.md
> +# 쿠버네티스 클러스터 아키텍처 이해
아키텍처 이미지 첨부 했습니다.

2023-05-18 05:19 UTC, HunkiKim commented on kubernetes/k8s-basic.md
> +            - 리더,팔로워,후보자 세 가지 역할로 노드를 구성하고 리더 선출, 로그 복제 등의 과정을 통해 분산시스템의 일관성을 유지한다고 하는데 자세하겐 모르겠습니다
말씀하신 용어들과 알고리즘에 대해서 정리하였습니다.

2023-05-18 05:19 UTC, HunkiKim commented on kubernetes/k8s-basic.md
> +    - 복제된 마스터 노드는 보통 활성화되지 않은 상태에서 필요할때 사용
수정했습니다!

2023-05-18 05:19 UTC, HunkiKim commented on kubernetes/k8s-basic.md
> +## Kube-proxy
kube-proxy이미지 첨부 및 내용 추가를 하였습니다.

2023-05-18 05:19 UTC, HunkiKim commented on kubernetes/k8s-basic.md
> +# 쿠버네티스 특징
간단한 특징 내용 추가했습니다

2023-05-22 05:02 UTC, mantech-mjkim requested changes

2023-05-22 05:02 UTC, mantech-mjkim commented on kubernetes/k8s-basic.md
> +# 마스터 노드
마스터 노드는 컨트롤 플레인 역할을 하는 노드이며 동일한 의미라고 생각하시면 될 것 같습니다.
마스터 노드의 내용이 마스터 노드 HA에 관련된 내용으로 내용 정리 다시 해주세요.

2023-05-22 05:02 UTC, mantech-mjkim commented on kubernetes/k8s-basic.md
> +- 즉 순서는 이렇습니다.
아래 순서가 맞는건가요?

2023-05-31 15:15 UTC, merged