feat: Pod Pattern을 쓰는 이유
HunkiKim/Mantech-Edu pull request #3
Opened 2023-05-15 02:13 UTC by HunkiKim

- 사이드카 패턴
- 앰버서더 패턴
- 어댑터 패턴

2023-05-15 13:11 UTC, mantech-mjkim requested changes
multi container를 사용하는 이유에 대해서 작성해주세요.

2023-05-18 05:20 UTC, HunkiKim commented
> multi container�를 사용하는 이유에 대해서 작성해주세요.

작성완료했습니다!

2023-05-24 04:22 UTC, mantech-mjkim requested changes
멀티 컨테이너 사용 이유
1. 멀티 컨테이너의 lifecyle이 동일한 경우 
2. 멀티 컨테이너가 높은 결합도를 보이는 경우, network 비용을 줄일 수 있음
3. 어플리케이션 영향도를 최소화 할 경우, 코드 변경 없이 배포 가능

2023-05-24 05:33 UTC, HunkiKim commented
> 멀티 컨테이너 사용 이유
> 
> 1. 멀티 컨테이너의 lifecyle이 동일한 경우
> 2. 멀티 컨테이너가 높은 결합도를 보이는 경우, network 비용을 줄일 수 있음
> 3. 어플리케이션 영향도를 최소화 할 경우, 코드 변경 없이 배포 가능

수정했습니다

2023-05-25 01:56 UTC, merged