feat: job
HunkiKim/Mantech-Edu pull request #6
Opened 2023-05-15 02:16 UTC by HunkiKim

- Job
- CronJob

2023-05-17 06:45 UTC, mantech-mjkim requested changes

2023-05-17 06:45 UTC, mantech-mjkim commented on kubernetes/job.md
> +- restartPolicy는 보통 Always로 설정되어 있기 때문에 Job으로 만들경우 항상 이를 **OnFailuer** or **Never**를 작성하여 재실행하지않게 한다.
restartPolicy는 Job 리소스에서만 설정가능한 고유 필드가 아닙니다.
`보통`이라는 건 왜 보통인 경우가 어떤건지 알려주세요. 그리고 Job에서는 restartPolicy를 Always를 사용할 수 없는지 설명이 필요합니다.

2023-05-17 06:45 UTC, mantech-mjkim commented on kubernetes/job.md
> +- 위의 manifest를 제출하면 처음엔 DESIRED로 되어있다. 완료되면 Completed로 표시되고 -a를 통해서만 볼 수 있다.
`DESIRED` 를 어디서 확인이 가능하며 flag는 어떤 플래그인가요?
command 조회 시 결과도 올려주세요.
참고로 `-a` flag는 없습니다.

2023-05-17 06:45 UTC, mantech-mjkim commented on kubernetes/job.md
> +    - 삭제하지 않으면 남아있다고 한다.
`남아있다고 한다.` 와 같은 부정확한 설명보다는 정확한 설명으로 작성해주세요.

2023-05-17 06:45 UTC, mantech-mjkim commented on kubernetes/job.md
> +- 추가적으로 **completions** 방식과 **parallelism** 방식이 있다.
두 필드 모두 방식이 아닙니다.

2023-05-17 06:45 UTC, mantech-mjkim commented on kubernetes/job.md
> +    - 만약 둘 다 같이 정의되어 있다면 parallelism으로 실행된 Job들중 하나가 Completed가 된다면 이후로 completions의 잡들이 순차적으로 실행된다.
설명이 잘못되었습니다.

2023-05-17 06:45 UTC, mantech-mjkim commented on kubernetes/job.md
> +        - 위처럼 변경하면 즉시 다른 파드가 기동돼, 세 개의 파드가 실행된다. 이를 **Job Scaling**이라고 한다.
command에 대한 예시도 항상 같이 넣어주세요.

2023-05-17 06:45 UTC, mantech-mjkim commented on kubernetes/job.md
> +- **activeDeadSeconds** 속성을 통해 파드가 일정시간 실행되면, 잡을 실패하는 것으로 간주하게 할 수 있다.
`activeDeadSeconds` 필드가 잘못되었고 설명이 부족합니다. 잡이 해당 속성으로 인하여 어떻게 파드가 종료되며 잡은 어떤 상태가 되는건지 설명이 필요합니다.

2023-05-17 06:45 UTC, mantech-mjkim commented on kubernetes/job.md
> +- 크론잡을 쓰면 된다.
전체적으로 설명이 부족합니다.

2023-05-17 06:45 UTC, mantech-mjkim commented on kubernetes/job.md
> +    ```json
예시가 잘못되었습니다.

2023-05-17 06:46 UTC, mantech-mjkim commented
전체적으로 스터디가 제대로 되었는지 산출물로 확인이 불가능합니다. 코멘트 확인하시고 k8s 공식 문서 등을 참조하여 스터디가 다시 필요합니다.

2023-05-18 05:21 UTC, HunkiKim commented on kubernetes/job.md
> +- restartPolicy는 보통 Always로 설정되어 있기 때문에 Job으로 만들경우 항상 이를 **OnFailuer** or **Never**를 작성하여 재실행하지않게 한다.
restartPolicy에 대해 수정하였고, 보통같은경우는 용어의 혼동이 있어 다시 정리했습니다. 또한 Job에서 Always를 사용할 수 없는 이유도 추가했습니다.

2023-05-18 05:22 UTC, HunkiKim commented on kubernetes/job.md
> +- 위의 manifest를 제출하면 처음엔 DESIRED로 되어있다. 완료되면 Completed로 표시되고 -a를 통해서만 볼 수 있다.
DESIRED와 -a같은 경우는 k8s in action에 있던 내용이며, 실제 실습해보려했을때 사용할 수 없어 내용에서 제외했습니다.

2023-05-18 05:22 UTC, HunkiKim commented on kubernetes/job.md
> +    - 삭제하지 않으면 남아있다고 한다.
내용 제거했습니다

2023-05-18 05:25 UTC, HunkiKim commented on kubernetes/job.md
> +- 추가적으로 **completions** 방식과 **parallelism** 방식이 있다.
필드로 변경했습니다!

2023-05-18 05:25 UTC, HunkiKim commented on kubernetes/job.md
> +    - 만약 둘 다 같이 정의되어 있다면 parallelism으로 실행된 Job들중 하나가 Completed가 된다면 이후로 completions의 잡들이 순차적으로 실행된다.
설명 다시 수정하였습니다

2023-05-18 05:25 UTC, HunkiKim commented on kubernetes/job.md
> +        - 위처럼 변경하면 즉시 다른 파드가 기동돼, 세 개의 파드가 실행된다. 이를 **Job Scaling**이라고 한다.
현재 실습 할 수 없어 자세한 실습내용 추가했습니다

2023-05-18 05:26 UTC, HunkiKim commented on kubernetes/job.md
> +- **activeDeadSeconds** 속성을 통해 파드가 일정시간 실행되면, 잡을 실패하는 것으로 간주하게 할 수 있다.
잘못된 부분 수정하였으며, 실습내용도 추가했습니다.

2023-05-18 05:26 UTC, HunkiKim commented on kubernetes/job.md
> +- 크론잡을 쓰면 된다.
좀 더 설명 추가했습니다

2023-05-18 05:26 UTC, HunkiKim commented on kubernetes/job.md
> +    ```json
예시를 수정하였으며, 잘못된 내용도 다시 수정하였습니다.

2023-05-24 05:44 UTC, mantech-mjkim requested changes

2023-05-24 05:44 UTC, mantech-mjkim commented on kubernetes/job.md
> +    - **completions** 필드은 순차적으로 Job 리소스를 생성한다.
completions 필드는 성공 횟수를 의미합니다.

2023-05-24 05:44 UTC, mantech-mjkim commented on kubernetes/job.md
> +    - 테스트를 할 수 있는 방법은 따로 없습니다.
개념적으로 이해하고 있어서 따로 테스트하지 않아도되고 해당 문장은 제거해주셔도 됩니다.

2023-06-04 04:17 UTC, merged